name: Pull requests

on:
  workflow_dispatch:

jobs:
  assemble_job:
    name: Assemble
    runs-on: ubuntu-22.04
    continue-on-error: true

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin

      - name: Build all configurations
        env:
          APK_BUILD: "true"
        run: ./gradlew assemble

      - name: Upload APK as Artifacts
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
            name: kiwix-android
            path: |
              **/*.apk
